global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'     # Self-monitoring
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter' # Host metrics (CPU, RAM, Disk, Net)
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: 'cloudwatch'   # AWS Lambda metrics from CloudWatch Exporter
    static_configs:
      - targets: ['cloudwatch-exporter:9106']