name: Serverless CI/CD

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run JavaScript Linter
        run: |
          npm install eslint -g
          eslint app.js --fix || true

  terraform:
    name: Validate & Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Format Check
        run: terraform fmt -check
        working-directory: terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: terraform

  deploy-frontend:
    name: Deploy Frontend to S3
    needs: [lint, terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload frontend to S3
        run: aws s3 sync . s3://adamwrona-serverless-frontend/ --exclude "terraform/*"

  deploy-lambda:
    name: Deploy AWS Lambda
    needs: [terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package Lambda
        run: |
          cd terraform
          zip -r lambda.zip lambda_function.py

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code --function-name serverless-backend --zip-file fileb://terraform/lambda.zip

      - name: Verify API after deployment
        run: |
          sleep 5  # Czekamy na propagację zmian
          curl -X GET https://uij5hsagih.execute-api.us-east-1.amazonaws.com/dev/tasks || exit 1
